[package]
edition = "2021"
name = "tools"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2"
colored = "2.0.0"
rust-embed = "6.4.0"
